#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

/**
 * Generates docs/cost.md from the environment files and a committed price
 * snapshot.
 *
 * The sizing is read out of `environments/*` rather than repeated here, so the
 * table cannot quietly disagree with the configuration it describes. A missing
 * value is an error, not a default — a cost table that silently assumes
 * something is worse than no cost table.
 *
 * infracost would do this better and needs an API key. This does not.
 */
const root = new URL('..', import.meta.url);
const prices = JSON.parse(readFileSync(new URL('scripts/prices.json', root), 'utf8'));

/** Pulls `key = value` out of an HCL file. Enough for scalar sizing values. */
function hcl(source, key) {
  const match = new RegExp(`^\\s*${key}\\s*=\\s*"?([^"\\n]+?)"?\\s*$`, 'm').exec(source);
  if (!match) throw new Error(`could not find "${key}" — the cost table would be guessing`);
  return match[1].trim();
}

function readEnvironment(name) {
  const source = readFileSync(new URL(`environments/${name}/main.tf`, root), 'utf8');

  return {
    name,
    natGateways: Number(hcl(source, 'nat_gateway_count')),
    instanceClass: hcl(source, 'instance_class'),
    storageGb: Number(hcl(source, 'allocated_storage_gb')),
    multiAz: hcl(source, 'multi_az') === 'true',
    desiredCount: Number(hcl(source, 'desired_count')),
    cpu: Number(hcl(source, 'cpu')),
    memory: Number(hcl(source, 'memory')),
    priceClass: hcl(source, 'price_class'),
    interfaceEndpoints: hcl(source, 'enable_interface_endpoints') === 'true',
    azCount: 2,
  };
}

export function estimate(env) {
  const { hoursPerMonth: hours, assumptions } = prices;

  const rdsHourly = prices.rds[env.instanceClass];
  if (rdsHourly === undefined) {
    throw new Error(`no price recorded for ${env.instanceClass}; add it to scripts/prices.json`);
  }

  // Fargate bills per vCPU-hour and per GB-hour, for the task's whole life.
  const vcpu = env.cpu / 1024;
  const memoryGb = env.memory / 1024;
  const fargate =
    env.desiredCount * hours * (vcpu * prices.fargateVcpuPerHour + memoryGb * prices.fargateGbPerHour);

  const nat =
    env.natGateways * hours * prices.natGatewayPerHour +
    assumptions.natEgressGbPerMonth * prices.natGatewayPerGb;

  // Interface endpoints are billed per endpoint per AZ. Four of them across two
  // AZs is eight hourly charges — which is why the README says they are worth
  // it for the NAT egress they remove, not that they are free.
  const endpoints = env.interfaceEndpoints
    ? 4 * env.azCount * hours * prices.vpcInterfaceEndpointPerHourPerAz
    : 0;

  const alb = hours * (prices.albPerHour + assumptions.albLcus * prices.albLcuPerHour);

  const rds =
    (env.multiAz ? 2 : 1) * hours * rdsHourly +
    (env.multiAz ? 2 : 1) * env.storageGb * prices.rdsStorageGbMonth;

  const logs = assumptions.logsGbPerMonth * prices.cloudwatchLogsIngestPerGb;
  const secret = prices.secretPerMonth;
  const cdn =
    assumptions.assetsGbStored * prices.s3StorageGbMonth +
    assumptions.cdnGbServed * prices.cloudfrontPerGb[env.priceClass];

  const lines = { fargate, nat, endpoints, alb, rds, logs, secret, cdn };
  const total = Object.values(lines).reduce((sum, value) => sum + value, 0);

  return { ...env, lines, total };
}

function money(value) {
  return `$${value.toFixed(2)}`;
}

function render(estimates) {
  const labels = {
    fargate: 'ECS Fargate',
    nat: 'NAT gateway',
    endpoints: 'VPC interface endpoints',
    alb: 'Application Load Balancer',
    rds: 'RDS PostgreSQL',
    logs: 'CloudWatch Logs',
    secret: 'Secrets Manager',
    cdn: 'S3 + CloudFront',
  };

  const header = `| line | ${estimates.map((e) => e.name).join(' | ')} |`;
  const divider = `| --- | ${estimates.map(() => '---:').join(' | ')} |`;

  const rows = Object.keys(labels).map(
    (key) => `| ${labels[key]} | ${estimates.map((e) => money(e.lines[key])).join(' | ')} |`,
  );

  const totals = `| **Total** | ${estimates.map((e) => `**${money(e.total)}**`).join(' | ')} |`;

  const sizing = estimates
    .map(
      (e) =>
        `| ${e.name} | ${e.desiredCount} × ${e.cpu}/${e.memory} | ${e.instanceClass}${e.multiAz ? ' (Multi-AZ)' : ''} | ${e.storageGb} GB | ${e.natGateways} | ${e.interfaceEndpoints ? 'yes' : 'no'} | ${e.priceClass} |`,
    )
    .join('\n');

  const largest = estimates.map((e) => {
    const [key] = Object.entries(e.lines).sort((a, b) => b[1] - a[1])[0];
    return `**${e.name}**: ${labels[key]}, ${money(e.lines[key])} of ${money(e.total)}`;
  });

  return `# Monthly cost

Generated by \`npm run cost\` from \`scripts/prices.json\` and the sizing in
\`environments/*/main.tf\`. Do not edit by hand.

**A list-price estimate, not a bill.** Prices captured ${prices.captured} for
${prices.region}, on demand. No Savings Plans, no Reserved Instances, no free
tier, no tax, and no data transfer beyond the assumptions below. AWS bills what
AWS bills.

## Sizing, read from the environment files

| environment | tasks × cpu/mem | database | storage | NAT | endpoints | CloudFront |
| --- | --- | --- | ---: | ---: | --- | --- |
${sizing}

## Estimate

${header}
${divider}
${rows.join('\n')}
${totals}

## Where the money goes

${largest.map((line) => `- ${line}`).join('\n')}

The NAT gateway is the line most people are surprised by: it costs the same
whether it passes a byte or a terabyte, which is why dev shares one and prod
runs one per availability zone.

The VPC interface endpoints are the line that changed a decision. They take
image pulls and log shipping off the NAT gateway's per-gigabyte charge, and
they are billed per endpoint per availability zone — four endpoints across two
AZs is eight hourly charges. Generating this table showed them costing more in
dev than the egress they save, so dev turns them off and prod leaves them on.
That is the number to check against your own traffic rather than copying the
answer.

## Assumptions

${Object.entries(prices.assumptions)
  .map(([key, value]) => `- \`${key}\`: ${value}`)
  .join('\n')}

Change these in \`scripts/prices.json\` and re-run. They are guesses about
traffic, and traffic is the thing this cannot know.
`;
}

const environments = ['dev', 'prod'].map(readEnvironment).map(estimate);
const output = new URL('docs/cost.md', root);

if (process.argv.includes('--check')) {
  const current = readFileSync(output, 'utf8');
  if (current !== render(environments)) {
    console.error('docs/cost.md is out of date — run `npm run cost` and commit the result');
    process.exit(1);
  }
  console.log('cost table matches the environment files');
} else {
  writeFileSync(output, render(environments));
  console.log(`wrote ${fileURLToPath(output)}`);
  for (const env of environments) console.log(`  ${env.name}: ${money(env.total)}/month`);
}
